--require('settings')
require('options')
require('autocmd')
require('mapping')
-- require('color-config.nightfox')
require('color-config.catppuccin')
-- require('color-config.kanagawa')
require('packer-config')
require('lsp-config')
require('treesitter-config')
require('mason-config')
require('cmp-config')
require('luasnip-config')
require('telescope-config')
require('devicons-config')
require('lualine-config')
require('oas-preview')
