require('options')
require('autocmd')
require('mapping')
require('lazy-config')
require('color-config.catppuccin')
-- require('color-config.nightfox')
-- require('color-config.kanagawa')
require('devicons-config')
require('lualine-config')
require('utils').setup()
-- require('oas-preview').setup({})
-- require('oas-preview').setup({api_route="http://127.0.0.1", port="1112", ui="swagger", auto_open_url=true})
