require("core")
require("lazy-config")
require("themes")
require("utils").setup()
-- require('oas-preview').setup({})
-- require('oas-preview').setup({api_route="http://127.0.0.1", port="1112", ui="swagger", auto_open_url=true})
