-- require('themes.color-config')
require("themes.color-config.catppuccin")
-- require('themes.color-config.nightfox')
-- require('themes.color-config.kanagawa')
require("themes.devicons-config")
require("themes.lualine-config")
