return {
	require("plugins.load.ccc"),
	require("plugins.load.codesnap"),
	require("plugins.load.comment"),
	require("plugins.load.common"),
	require("plugins.load.completion"),
	require("plugins.load.conform"),
	require("plugins.load.curl"),
	require("plugins.load.cursor-animate"),
	require("plugins.load.dap"),
	require("plugins.load.git"),
	require("plugins.load.lsp"),
	require("plugins.load.markdown-preview"),
	require("plugins.load.mini"),
	require("plugins.load.noice"),
	-- require("plugins.load.noice2"),
	-- require("plugins.load.noice3"),
	-- require("plugins.load.nonels"),
	require("plugins.load.notify"),
	require("plugins.load.nvim-colorizer"),
	require("plugins.load.oil"),
	require("plugins.load.styles"),
	require("plugins.load.telescope"),
	require("plugins.load.treesitter"),
	require("plugins.load.trouble"),
	require("plugins.load.ufo"),
	require("plugins.load.harpoon"),
}
